defaults:
  - env/HABOpenSubtask@env.train
  - env/HABOpenSubtask@env.eval
  - model/openvla_oft@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: all
    env: all
    rollout: all

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "maniskillhab_ppo_openvlaoft"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 1
  seq_length: 4096
  max_prompt_length: 30

algorithm:
  update_epoch: 1
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  reward_coef: 1.0

  rollout_epoch: 1
  eval_rollout_epoch: 1 # set eval_rollout_epoch > 0 when enable runner.only_eval or runner.val_check_interval > 0
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: chunk_level
  
  adv_type: gae
  loss_type: actor_critic
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0


  gamma: 0.99
  gae_lambda: 0.95

  # params for rollout
  sampling_params:
    do_sample: True
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: -1
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  enable_offload: False

  # Override the default values in env/HABPickSubtask
  train:
    total_num_envs: 8
    auto_reset: True
    use_fixed_reset_state_ids: False
    max_episode_steps: 100 # max episode steps for truncation
    max_steps_per_rollout_epoch: 100
    use_instruction: True
  eval:
    total_num_envs: 8
    auto_reset: True
    ignore_terminations: True
    max_episode_steps: 100
    max_steps_per_rollout_epoch: 100
    use_fixed_reset_state_ids: True
    group_size: 1
    video_cfg:
      save_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: False
  pipeline_stage_num: 1

  model:
    model_path: "/mnt/public/chenjiawei/logs_and_checkpoint/openvla-7b+mshab_prepare_groceries+b48+lr-0.0005+lora-r32+dropout-0.0--image_aug--no_action_head_only_fridge_state42_action13_only_success_depth_vla7b--5000_chkpt"
    precision: ${actor.model.precision}

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 10
  global_batch_size: 200
  seed: 1234
  enable_offload: False

  # Override the default values in model/mlp_policy
  model:
    model_path: "/mnt/public/chenjiawei/logs_and_checkpoint/openvla-7b+mshab_prepare_groceries+b48+lr-0.0005+lora-r32+dropout-0.0--image_aug--no_action_head_only_fridge_state42_action13_only_success_depth_vla7b--5000_chkpt"
    model_type: "openvla_oft"
    unnorm_key: mshab_prepare_groceries  # 'fetch_minmax' for debug
    policy_setup: "fetch"
    num_action_chunks: 8 # interface for the env
    action_dim: 13
    add_value_head: True
    image_size: [224, 224]
    is_lora: False
    lora_rank: 32
    # lora_path: /mnt/mnt/public/hongzhi/models/oft-sft/lora_004000/
    ckpt_path: null
    use_wrist_image: True
    num_images_in_input: 2
    attn_implementation: "flash_attention_2"
    low_cpu_mem_usage: True
    trust_remote_code: True
    gradient_checkpointing: True

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0
    critic_warmup_steps: 0

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    tokenizer_model: "/mnt/public/chenjiawei/logs_and_checkpoint/openvla-7b+mshab_prepare_groceries+b48+lr-0.0005+lora-r32+dropout-0.0--image_aug--no_action_head_only_fridge_state42_action13_only_success_depth_vla7b--5000_chkpt"
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

  # Override the default values in training_backend/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    gradient_checkpointing: False # for openpi, gradient checkpointing is not supported, please do not change this value
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}
reward:
  use_reward_model: False

critic:
  use_critic_model: False