seed: 2337
env:
  env_id: OpenSubtaskTrain-v0
  num_envs: 189
  max_episode_steps: 100
  make_env: true
  continuous_task: true
  cat_state: true
  cat_pixels: false
  frame_stack: 3
  stationary_base: false
  stationary_torso: false
  stationary_head: true
  task_plan_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/set_table/open/train/fridge.json
  spawn_data_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/set_table/open/train/spawn_data.pt
  record_video: false
  debug_video: false
  debug_video_gen: false
  save_video_freq: null
  info_on_video: false
  extra_stat_keys: []
  env_kwargs:
    robot_force_mult: 0.001
    robot_force_penalty_min: 0.2
    target_randomization: false
    randomly_slightly_open_articulation: false
eval_env:
  env_id: OpenSubtaskTrain-v0
  num_envs: 63
  max_episode_steps: 200
  make_env: true
  continuous_task: true
  cat_state: true
  cat_pixels: false
  frame_stack: 3
  stationary_base: false
  stationary_torso: false
  stationary_head: true
  task_plan_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/set_table/open/train/fridge.json
  spawn_data_fp: ~/.maniskill/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/set_table/open/train/spawn_data.pt
  record_video: false
  debug_video: false
  debug_video_gen: false
  save_video_freq: 10
  info_on_video: false
  extra_stat_keys: []
  env_kwargs:
    robot_force_mult: 0.001
    robot_force_penalty_min: 0.2
    target_randomization: false
    randomly_slightly_open_articulation: false
algo:
  name: ppo
  total_timesteps: 15000000
  learning_rate: 0.0003
  anneal_lr: false
  gamma: 0.9
  gae_lambda: 0.9
  num_minibatches: 16
  update_epochs: 8
  norm_adv: true
  clip_coef: 0.2
  clip_vloss: false
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  target_kl: 0.2
  log_freq: 10000
  save_freq: 100000
  eval_freq: 100000
  finite_horizon_gae: true
  torch_deterministic: true
  save_backup_ckpts: false
  eval_episodes: 189
  num_steps: 100
  num_envs: 189
  num_eval_envs: 63
  batch_size: 18900
  minibatch_size: 1181
  num_iterations: 794
logger:
  workspace: mshab_exps
  exp_name: rcad-set_table-open-fridge
  clear_out: true
  tensorboard: true
  wandb: false
model_ckpt: "mshab_checkpoints/rl/set_table/open/fridge/policy.pt"
